var txt = {
	Idioma: "",
};

var idiomas = {
	"ES":{
		"tit_terminos": "Términos y Condiciones",
		"tit_buscapunto":"Buscar Punto",
		"msj_terminos": "Los siguientes términos y condiciones (los \"Términos y Condiciones\") rigen el uso que usted le dé a esta aplicación y a cualquiera de los contenidos disponibles por o a través de esta aplicación, incluyendo cualquier contenido derivado del mismo. Fedearroz. (\"Fedearroz.\" o \"nosotros\") ha puesto a su disposición esta aplicación. Podemos cambiar los Términos y Condiciones de vez en cuando, en cualquier momento sin ninguna notificación. AL USAR LA APLICACIÓN, USTED ACEPTA Y ESTÉ DE ACUERDO CON ESTOS TÉRMINOS Y CONDICIONES EN LO QUE SE REFIERE A SU USO DE LA APP. Si usted no está de acuerdo con estos Términos y Condiciones, no puede tener acceso al mismo ni usar el App de ninguna otra manera.",
		"btn_aceptaterminos":"Aceptar",
		"btn_cancelar":"Cancelar",
		"ph_buscasitio":"Buscar lugar...",
		"tit_opciones":"Opciones",
		"tit_mapabase":"MAPA BASE",
		"tit_idioma":"IDIOMA",
		"tit_epoca_cultivo":"Época de cultivo",
		"tit_pronostico":"Predicción climática",
		"tit_clima":"Clima",
		"tit_tiempo":"Tiempo",
		"tit_tiempoAtmosferico":"Tiempo Atmosférico",
		"msj_map_calle":"Calles",
		"msj_map_topo":"Topográfico",
		"msj_map_satelite":"Satélite",
		"msj_latitud":"Latitud      p.e. 4.123456",
		"msj_longitud":"Longitud   p.e. -74.123456",
		"msj_norte":"Norte",
		"msj_sur":"Sur",
		"msjSiembra": "Siembra",
		"msjCosecha": "Cosecha",
		"msjPrecipitacion": "Precipitación",
		"msjRango": "Rango",
		"msjTemperatura": "Temperatura",
		"msjEpoca": "Cultivo",
		"msjMapa": "Mapa",
		"msjProduccion": "Producción",
		"msjMax": "Máximo",
		"msjMin": "Mínimo",
		"msjPromedio":"Promedio",
		"msjRiegoSuper": "Riego Superficie",
		"msjRiegoProd": "Riego Producción",
		"msjRiegoRend": "Riego Rendimiento",
		"msjRiegoMin": "Riego Mínimo",
		"msjRiegoMax": "Riego Máximo",
		"msjSecanoSuper": "Secano Superficie",
		"msjSecanoProd": "Secano Producción",
		"msjSecanoRend": "Secano Rendimiento",
		"msjSecanoMin": "Secano Mínimo",
		"msjSecanoMax": "Secano Máximo",
		"msjSinInfo": "No Disponible",
		"msjclimogramaTemPre": "Climograma (Temperatura / Precipitación)",
		"msjclimogramaHumSol": "Climograma (Humedad Relativa / Brillo Solar)",
		"msjclimogramaHumedadrelativa": "Humedad Relativa",
		"msjclimogramaBrillosolar": "Brillo Solar",
		"msjMicultivo": "Mis Cultivos",
		"msjAddcultivo": "Adicionar Cultivo",
		"msjNogps":"Ubicación NO encontrada!",
		"dialogGPSMensaje":"Su GPS está apagado, Esta aplicación requiere que este activo para todas sus funciones.",
		"dialogGPSDescripcion":"Use GPS, con wifi o Red celular.",
		"dialogGPSTitulo":"Por favor encienda su GPS",
		"msjSi":"Si",
		"msjNo":"No",
		"msjToneladas":"En Toneladas(Ton) ",
		"msjSinestacion":"No hay datos disponibles en el momento para esta úbicación!",
		"msjUbicacionmapa":"Ubicación tomada del punto en el mapa",
		"msjHectarea":"Hectárea",
		"msjRecomendacion":"Alerta",
		"msjNombre":"Nombre",
		"msjDetalle":"Detalle",
		"msjIr":"Ir",
		"msjEliminar":"Eliminar",
		"msjFechasiembra":"Fecha emergencia",
		"msjFechacosecha":"Fecha Cosecha",
		"msjVariedad":"Variedad",
		"msjSistema":"Sistema",
		"msjHectareacultivadas":"Hectáreas cultivadas",
		"msjFase":"Fase",
		"msjGuardar":"Guardar",
		"msjEliminacultivo":"Seguro desea eliminar el Cultivo: ",
		"msjEliminadocorrectamente":"Eliminado Correctamente!",
		"msjNoelimina":" No se puede eliminar ",
		"msjPrecipitacionacumdiaria":" Precipitación acumulada diaria ",
		"msjRadiacionacumdiaria":" Radiación acumulada diaria ",
		"msjEstacion":" Estación ",
		"msjDistancia":" Distancia ",
		"msjBajo":" Bajo ",
		"msjNormal":" Normal ",
		"msjSobre":" Sobre ",
		"msjA":" A ",
		"msjInfmensualperiodo": "Información Mensual - Periodo ",
		"msjEne": "Ene.",
		"msjFeb": "Feb.",
		"msjMar": "Mar.",
		"msjAbr": "Abr.",
		"msjMay": "May.",
		"msjJun": "Jun.",
		"msjJul": "Jul.",
		"msjAgo": "Ago.",
		"msjSep": "Sep.",
		"msjOct": "Oct.",
		"msjNov": "Nov.",
		"msjDic": "Dic.",
		"msjPrimersemestre": "Primer semestre",
		"msjSegundosemestre": "Segundo semestre",
		"msjEpocaFavorable": "Época favorable para ",
		"msjEpocaNoFavorable": "Época No favorable para ",
		"msjInicio": "Inicio ",
		"msjFin": "Inicio ",
		"msjLocalizando": "Localizando...",
		"msjRequerido": " requerido.",
		"msjDecadal":"Década",
		"msjRendimiento": "Rendimiento",
		"msjUndBrilloSol": " Hrs Prom.",
		"tit_decadal": "Acumulados o promedios de 10 días",
		"msjAcumulada": " Acum. ",
		"msjBultos": "Bultos/ha",
		"msjHistorico": " Historico",
		"msjProbabilidad":"Probabilidad",
		"msjSol":"Sol",
		"msjTrimestre":"Trimestre",
		"msjAlteracionprecipitacion":"Alteración en la precipitación",
	},
	"EN":{
		"tit_terminos": "Terms and Conditions",
		"tit_buscapunto":"Search point",
		"msj_terminos": "The following terms and conditions (the \"Terms and Conditions \") govern the use you give to this website and any of the content available on or through this website, including any content derivative thereof (the \" Website\"). Time Inc. (\"Time Inc. \" or \"we \") has made available the Website. We may change the Terms and Conditions from time to time at any time without notice, only publishing the changes on the Website. BY USING THE WEB SITE, YOU ACCEPT AND AGREE TO THESE TERMS AND CONDITIONS WITH REGARD TO YOUR USE OF THE WEB SITE. If you do not agree to these Terms and Conditions, you may not have access to it or use the Website in any other way.",
		"btn_aceptaterminos":"I agree",
		"btn_cancelar":"Cancel",
		"ph_buscasitio":"Search place...",
		"tit_opciones":"Options",
		"tit_mapabase":"BASE MAPS",
		"tit_idioma":"LANGUAGE",
		"tit_epoca_cultivo":"Growing season",
		"tit_pronostico":"Climate prediction",
		"tit_clima":"Weather",
		"tit_tiempo":"Weather",
		"tit_tiempoAtmosferico":"Weather",
		"msj_map_calle":"Streets",
		"msj_map_topo":"Topographic",
		"msj_map_satelite":"Satellite",
		"msj_latitud":"Latitude   e.g.  4.123456",
		"msj_longitud":"Longitude   e.g. -74.123456",
		"msj_norte":"North",
		"msj_sur":"South",
		"msjSiembra": "Sowing",
		"msjCosecha": "Harvest",
		"msjPrecipitacion": "Precipitation",
		"msjRango": "Range",
		"msjTemperatura": "Temperature",
		"msjEpoca": "Season",
		"msjMapa": "Map",
		"msjProduccion": "Production",
		"msjMax": "Maximum",
		"msjMin": "Minimum",
		"msjPromedio":"Average",
		"msjRiegoSuper": "Irrigation Surface",
		"msjRiegoProd": "Irrigation Production",
		"msjRiegoRend": "Irrigation Performance",
		"msjRiegoMin": "Irrigation Minimum ",
		"msjRiegoMax": "Irrigation Maximum",
		"msjSecanoSuper": "Dry farming Surface",
		"msjSecanoProd": "Dry farming Production",
		"msjSecanoRend": "Dry farming Performance",
		"msjSecanoMin": "Dry farming Minimum",
		"msjSecanoMax": "Dry farming Maximum",
		"msjSinInfo": "Unavailable",
		"msjclimogramaTemPre": "Weather graphic / Precipitation",
		"msjclimogramaHumSol": "Relative humidity / solar brightness",
		"msjclimogramaHumedadrelativa": "Relative Humidity",
		"msjclimogramaBrillosolar": "Solar Brightness",
		"msjMicultivo": "My Crops",
		"msjAddcultivo": "Add Crop",
		"msjNogps":"No GPS locations have been found!",
		"dialogGPSMensaje":"Your GPS is Disabled, this app needs to be enable to works.",
		"dialogGPSDescripcion":"Use GPS, with wifi or 3G.",
		"dialogGPSTitulo":"Please Turn on GPS",
		"msjSi":"Yes",
		"msjNo":"No",
		"msjToneladas":"In Tonnes(Ton) ",
		"msjSinestacion":"Data not available at the time",
		"msjUbicacionmapa":"Location taken from point on the map",
		"msjHectarea":"Hectare",
		"msjRecomendacion":"Alert",
		"msjNombre":"Name",
		"msjDetalle":"Details",
		"msjIr":"Go",
		"msjEliminar":"Delete",
		"msjFechasiembra":"Emergency date",
		"msjFechacosecha":"Harvest date",
		"msjVariedad":"Variety",
		"msjSistema":"System",
		"msjHectareacultivadas":"hectares cultivated",
		"msjFase":"Phase",
		"msjGuardar":"Save",
		"msjEliminacultivo":"Do you really want to remove this Crop: ",
		"msjEliminadocorrectamente":"successfully deleted!",
		"msjNoelimina": " Cannot drop ",
		"msjPrecipitacionacumdiaria":" Precipitation - daily totals ",
		"msjRadiacionacumdiaria":" Radiation - daily totals ",
		"msjEstacion":" Station ",
		"msjDistancia":" Distance ",
		"msjBajo":" Low ",
		"msjNormal":" Normal ",
		"msjSobre":" Upon ",
		"msjA":" to ",
		"msjInfmensualperiodo": "Monthly briefings - Period ",
		"msjEne": "Jan.",
		"msjFeb": "Feb.",
		"msjMar": "Mar.",
		"msjAbr": "Apr.",
		"msjMay": "May.",
		"msjJun": "Jun.",
		"msjJul": "Jul.",
		"msjAgo": "Aug.",
		"msjSep": "Sep.",
		"msjOct": "Oct.",
		"msjNov": "Nov.",
		"msjDic": "Dec.",
		"msjPrimersemestre": "The first Half of the year",
		"msjSegundosemestre": "The second half of the year",
		"msjEpocaFavorable": "Favorable moment for ",
		"msjEpocaNoFavorable": "Inauspicious moment for ",
		"msjInicio": "Start ",
		"msjFin": "Finish ",
		"msjLocalizando": "Locating...",
		"msjRequerido": " required.",
		"msjDecadal":"Decade",
		"msjRendimiento": "Performance",
		"msjUndBrilloSol": " Hrs Avg.",
		"tit_decadal": "Accumulated or average of 10 days",
		"msjAcumulada": " Accum. ",
		"msjBultos": "packages/he",
		"msjHistorico": " Old records",
		"msjProbabilidad":"probability",
		"msjSol":"Sun",
		"msjTrimestre":"Quarter",
		"msjAlteracionprecipitacion":"changes in rainfall patterns",
	}
};

function SetIdioma(leng){ console.log("Cambio de idioma:" +leng);
	txt.Idioma = leng;
	$.each( idiomas[leng], function( key, value ) {
		txt[key] = value;		//console.log ( key + ": " + value );
	});
	$("#lugares").attr("placeholder", txt.ph_buscasitio);
	$("#btn_opciones").find('button').html('<i class="fa fa-cog" aria-hidden="true"></i> '+txt.tit_opciones);
	$("#btn_opcProduccion").find('button').html('<i class="fa fa-stack-overflow" aria-hidden="true"></i> ' + txt.msjProduccion);
	$("#btn_opcClima").find('button').html('<i class="fa fa-cloud" aria-hidden="true"></i> '+txt.tit_clima);
	$("#btn_opcMicultivo").find('button').html('<i class="fa fa-th-list" aria-hidden="true"></i> '+txt.msjMicultivo);
	$(".tit_popup").html(txt.msjProduccion);
	$(".msjRiegoSuper").html(txt.msjRiegoSuper);
	$(".msjRiegoProd").html(txt.msjRiegoProd);
	$(".msjRiegoRend").html(txt.msjRiegoRend);
	$(".msjRiegoMin").html(txt.msjRiegoMin);
	$(".msjRiegoMax").html(txt.msjRiegoMax);
	$(".msjSecanoSuper").html(txt.msjSecanoSuper);
	$(".msjSecanoProd").html(txt.msjSecanoProd);
	$(".msjSecanoRend").html(txt.msjSecanoRend);
	$(".msjSecanoMin").html(txt.msjSecanoMin);
	$(".msjSecanoMax").html(txt.msjSecanoMax);
	$(".msjSinInfo").html(txt.msjSinInfo);
	$("#localizando").html(txt.msjLocalizando);
	
/*	$.each( txt, function( key, value ) {console.log ( key + ": " + value );});	*/	
};